### ISSUE TITLE
Invariant Violation: Cannot find a route named "home"

### ISSUE THREAD

**Issue by michalsanger** [steida/este-todomvc#1]
Just made ```npm i``` and ```gulp -p```, opened ```localhost:8000```, app is running but in console I see this:
```
Error: Invariant Violation: Cannot find a route named "home"
    at invariant (/private/tmp/este-todomvc/node_modules/react/lib/invariant.js:42:15)
    at Function.makePath (/private/tmp/este-todomvc/node_modules/react-router/lib/createRouter.js:183:11)
    at Function.makeHref (/private/tmp/este-todomvc/node_modules/react-router/lib/createRouter.js:196:25)
    at [object Object].makeHref (/private/tmp/este-todomvc/node_modules/react-router/lib/Navigation.js:46:25)
    at [object Object].getHref (/private/tmp/este-todomvc/node_modules/react-router/lib/components/Link.js:77:17)
    at [object Object].render (/private/tmp/este-todomvc/node_modules/react-router/lib/components/Link.js:100:18)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactCompositeComponent.js:802:14)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/private/tmp/este-todomvc/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/private/tmp/este-todomvc/node_modules/react/lib/ReactDOMComponent.js:260:32)
    at ReactDOMComponent.Mixin.mountComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactDOMComponent.js:182:14)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/private/tmp/este-todomvc/node_modules/react/lib/ReactCompositeComponent.js:808:44)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/private/tmp/este-todomvc/node_modules/react/lib/ReactMultiChild.js:195:42)
    at ReactDOMComponent.Mixin._createContentMarkup (/private/tmp/este-todomvc/node_modules/react/lib/ReactDOMComponent.js:260:32)
```

**Comment by steida** [comment]
Hmm, once I had the same problem. Something with react-router, thank you for report.

**Comment by steida** [comment]
Should be fixed now. Try it please.

**Comment by michalsanger** [comment]
Confirmed, well done.
